# Generated by Django 3.2.21 on 2023-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_do_estado_estadosbrasileiros_nome_do_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosbrasileiros',
            name='latidade',
            field=models.CharField(default='vou arrumar', max_length=15),
        ),
        migrations.AddField(
            model_name='estadosbrasileiros',
            name='longitude',
            field=models.CharField(default='vou arrumar', max_length=15),
        ),
    ]
