# Generated by Django 3.2.21 on 2023-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230928_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadosbrasileiros',
            old_name='latidade',
            new_name='latitude',
        ),
    ]
